"""Constants and configuration values for taste profile analysis."""

from .aspects import (
    ASPECT_MAPPING,
    ASPECT_RELATIONSHIPS,
    ASPECT_WEIGHTS,
    COMPOUND_ASPECTS,
    QUALITY_INDICATORS,
)
from .languages import (
    CERTIFICATION_KEYWORDS,
    DINING_STYLE_KEYWORDS,
    INTENSITY_MODIFIERS,
    NEGATION_WORDS,
    PRICE_KEYWORDS,
    SUPPORTED_LANGUAGES,
)
from .thresholds import (
    BATCH_SIZE,
    CACHE_SIZE,
    CONFIDENCE_BOOST_PER_MENTION,
    MAX_CLUSTERS,
    MAX_CONFIDENCE_SCORE,
    MIN_CLUSTERS,
    MIN_CONFIDENCE_THRESHOLD,
    MIN_MENTIONS_FOR_RELIABLE_SCORE,
    MIN_REVIEWS_THRESHOLD,
    MIXED_SENTIMENT_VARIANCE_THRESHOLD,
    MODEL_NAME,
    PRICE_CATEGORY_THRESHOLDS,
    PRICE_MODIFIERS,
    REVIEW_WEIGHT_DECAY,
    SENTIMENT_RANGES,
    SILHOUETTE_THRESHOLD,
    VALUE_RATIO_THRESHOLDS,
)

__all__ = [
    # Aspects
    "ASPECT_MAPPING",
    "COMPOUND_ASPECTS",
    "ASPECT_WEIGHTS",
    "QUALITY_INDICATORS",
    "ASPECT_RELATIONSHIPS",
    # Languages
    "SUPPORTED_LANGUAGES",
    "NEGATION_WORDS",
    "INTENSITY_MODIFIERS",
    "PRICE_KEYWORDS",
    "DINING_STYLE_KEYWORDS",
    "CERTIFICATION_KEYWORDS",
    # Thresholds
    "MIN_CONFIDENCE_THRESHOLD",
    "MIN_REVIEWS_THRESHOLD",
    "MIN_CLUSTERS",
    "MAX_CLUSTERS",
    "SILHOUETTE_THRESHOLD",
    "MODEL_NAME",
    "BATCH_SIZE",
    "CACHE_SIZE",
    "SENTIMENT_RANGES",
    "PRICE_MODIFIERS",
    "PRICE_CATEGORY_THRESHOLDS",
    "VALUE_RATIO_THRESHOLDS",
    "MIXED_SENTIMENT_VARIANCE_THRESHOLD",
    "CONFIDENCE_BOOST_PER_MENTION",
    "MAX_CONFIDENCE_SCORE",
    "MIN_MENTIONS_FOR_RELIABLE_SCORE",
    "REVIEW_WEIGHT_DECAY",
]
